source 'https://rubygems.org'
gem 'bundler'
gem 'rake'
gem 'rack'
gem 'thin'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'nokogiri', "1.5.5"

gem "cedilla"

group :test do
  gem 'webmock', "~> 1.17.4"
end
