source 'https://rubygems.org'
gem 'rake'
gem 'rack'
gem 'thin'
gem 'sinatra'
gem 'sinatra-contrib'
#gem 'rdf-rdfxml'
#gem 'json-ld'
#gem 'equivalent-xml'
gem 'oclc-auth'
gem 'worldcat-discovery'

gem "cedilla"

group :test do
  gem 'webmock', "~> 1.17.4"
end
