source 'https://rubygems.org'
gem 'rake'
gem 'rack'
gem 'thin'
gem 'sinatra'
gem 'sinatra-contrib'

gem "cedilla", :path => "~/Documents/workspace/cedilla_ruby" 

group :test do
  gem 'webmock', "~> 1.17.4"
end